local:
    addr: 127.0.0.1:8090
    runmode: debug
    crongraph: "0 */5 * * * ?"
    croncodis: "0 */3 * * * ?"
    estimediff: 600
    logpath: "./logs/codisgraph.log"
    codisurl: "http://www.codis.com/"

mysql:
    name: codisdb
    addr: 127.0.0.1:3308
    username: root
    password: 123456

elasticsearch:
    addr: http://172.30.1.3:9200
    index: codis-proxy
    doctype: codis-proxy
    user: root
    password: xxxxxxxxxxxxxxx